### ISSUE TITLE
Update 3D Tiles temporal pipeline in Computations folder

### ISSUE THREAD

**Issue by jailln** [VCityTeam/UD-Reproducibility#1]
The pipeline for computing 3D Tiles temporal tilesets in [Computations/ComputeLyon3DTilesTemporal](https://github.com/VCityTeam/UD-Reproducibility/tree/master/Computations/ComputeLyon3DTilesTemporal) has been improved for an article in [Articles/2020-IJGIS-Temporal/Compute3DTiles](https://github.com/VCityTeam/UD-Reproducibility/tree/master/Articles/2020-IJGIS-Temporal/Compute3DTiles).

This 'computation' pipeline ([Computations/ComputeLyon3DTilesTemporal](https://github.com/VCityTeam/UD-Reproducibility/tree/master/Computations/ComputeLyon3DTilesTemporal)) must be updated to the 'article' version of the pipeline ([Articles/2020-IJGIS-Temporal/Compute3DTiles](https://github.com/VCityTeam/UD-Reproducibility/tree/master/Articles/2020-IJGIS-Temporal/Compute3DTiles)).

**Comment by jailln** [comment]
@EricBoix I think you've resolved this issue ?

**Comment by EricBoix** [comment]
Let's say I did (for real, there were so many changes on the master that I lost track).
Closing.
